### ISSUE TITLE
Không thể cài được thông qua composer

### ISSUE THREAD

**Issue by hoangnamitc** [momo-wallet/php#2]
Xin chào.

Tôi cài đặt thông qua composer thì báo lỗi sau:
![image](https://user-images.githubusercontent.com/7042462/67649724-cd708b80-f96c-11e9-84e3-bf8762bdb671.png)

**Comment by MrCorncob** [comment]
đây là do minimum-stability trong composer.json của bạn chưa được set hoặc set level cao hơn release của momo.
Bạn set lại thành như vầy là cài được nhé (key này nằm trong root level)
`"minimum-stability": "dev",`
